public class SalesforceDeveloper {

    public void myFirstCode(){

        string sehir = 'Istanbul';
        system.debug(sehir);

        string film = 'Temmuzda';
        system.debug(film);

        string mevsim = 'Yaz';
        system.debug(mevsim);
        
    }

    public void myFavorites(){
        string myHomeTown = 'Sarasota';
        system.debug(myHomeTown);

        integer myFavNum = 4;
        system.debug(myFavNum);
        
        system.debug('Favori Numaram  ==> ' + myFavNum + ', yasadigim yer ==> ' + myHomeTown);

    }


}